#!/usr/bin/env node
// Codegen: vendor Phosphor UI glyphs as node sigils.
// Reads flowey/icons/catalog.json + flowey/icons/phosphor/*.svg (paths are
// relative to the repo root; no absolute paths) and emits
// renderers/shared/generated-sigils.mjs. Follows the same banner + --check
// convention as scripts/generate-brand-marks.mjs.

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(here, '..');
const iconsDir = path.join(root, 'icons', 'phosphor');
const catalogPath = path.join(root, 'icons', 'catalog.json');
const outputPath = path.join(root, 'renderers', 'shared', 'generated-sigils.mjs');
const checkOnly = process.argv.includes('--check');

function fail(message) {
  console.error(`sigil catalog: ${message}`);
  process.exit(1);
}

const catalog = JSON.parse(fs.readFileSync(catalogPath, 'utf8'));
const glyphs = catalog.glyphs || {};
const names = Object.keys(glyphs).sort();
if (names.length === 0) fail('catalog.json must contain a non-empty glyphs map');

const TONES = new Set(['actor', 'action', 'decision', 'milestone', 'place', 'document', 'record', 'outcome', 'group', 'external']);
const entries = names.map((name) => {
  if (!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(name)) fail(`invalid glyph name ${JSON.stringify(name)}`);
  const meta = glyphs[name] || {};
  if (!TONES.has(meta.tone)) fail(`glyph ${name} has invalid tone ${JSON.stringify(meta.tone)}`);
  const file = path.join(iconsDir, `${name}.svg`);
  if (!fs.existsSync(file)) fail(`missing vendored file icons/phosphor/${name}.svg`);
  const svg = fs.readFileSync(file, 'utf8');
  const viewBox = /viewBox="([^"]+)"/.exec(svg)?.[1] || '';
  if (viewBox !== '0 0 256 256') fail(`glyph ${name} has unexpected viewBox ${JSON.stringify(viewBox)}`);
  const inner = svg.replace(/^[\s\S]*?<svg[^>]*>/, '').replace(/<\/svg>\s*$/, '').trim();
  if (!inner || !inner.includes('<path')) fail(`glyph ${name} has no path content`);
  if (/<script|on\w+=|javascript:/i.test(inner)) fail(`glyph ${name} contains active content`);
  return { name, tone: meta.tone, tags: [...new Set((meta.tags || []).map(String))].sort(), inner };
});

const banner = '// Generated by scripts/generate-sigils.mjs from icons/catalog.json + icons/phosphor/*.svg.\n// Phosphor Icons (MIT). Do not edit by hand.\n';
const source = `${banner}export const GENERATED_SIGILS = Object.freeze(${JSON.stringify(entries, null, 2)});\n`;

if (checkOnly) {
  const current = fs.existsSync(outputPath) ? fs.readFileSync(outputPath, 'utf8') : '';
  if (current !== source) {
    console.error('generated sigils are stale — run node scripts/generate-sigils.mjs');
    process.exit(1);
  }
  console.log(`sigils fresh (${entries.length} glyphs)`);
  process.exit(0);
}

fs.writeFileSync(outputPath, source);
console.log(`generated ${path.relative(root, outputPath)} (${entries.length} glyphs)`);
